services:
  - type: web
    name: acuasan
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 8000
    # disk: # Uncomment if using a paid plan for persistence
    #   name: acuasan-data
    #   mountPath: /app/backend/data
    #   sizeGB: 1
